POST http://localhost:5000/users
{
   
    "email": "john.doe@example.com",
    "password": "password123",
}
###
get http://localhost:5000/infos
###
get http://localhost:5000/Asesors
###
get http://localhost:5000/Products